apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: kube-system
data:
  actions.yaml: |
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 3 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: {{ .Values.daysToKeep | default 7 }}
          exclude:
  config.yaml: |
    client:
      hosts:
      - "elasticsearch-logging"
      port: 9200
---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: es-curator
  namespace: kube-system
spec:
  # Run at midnight
  schedule: "5 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: bobrik/curator
            imagePullPolicy: Always
            args:
            - --config=/config/config.yaml
            - /config/actions.yaml
            volumeMounts:
            - name: config
              mountPath: /config
          volumes:
          - name: config
            configMap:
              name: curator-config
          restartPolicy: OnFailure
